// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CompleteTodo(ctx context.Context, arg CompleteTodoParams) (Todo, error)
	CreateTodo(ctx context.Context, title string) (Todo, error)
	DeleteTodoByID(ctx context.Context, id int32) error
	GetAllTodo(ctx context.Context, arg GetAllTodoParams) ([]Todo, error)
	GetTodoByID(ctx context.Context, id int32) (Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
